project_id = "zsybxembykxiykgkdlth"

[functions.transcribe-audio]
verify_jwt = true

[functions.translate-message]
verify_jwt = true

[functions.summarize-content]
verify_jwt = true

[functions.parse-document-content]
verify_jwt = true