project_id = "zsybxembykxiykgkdlth"

[functions.generate-study-plan]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true

[functions.generate-flashcards]
verify_jwt = true

[functions.summarize-content]
verify_jwt = true

[functions.initialize-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = true

[functions.parse-document]
verify_jwt = true

[functions.parse-document-content]
verify_jwt = true